import { SCENE_PALETTE } from './palette'

export const SCENE_THEME = {
  palette: {
    ink: SCENE_PALETTE.ink,
    inkSoft: SCENE_PALETTE.inkSoft,
    paper: SCENE_PALETTE.paper,
    cream: SCENE_PALETTE.cream,
    creamLight: SCENE_PALETTE.creamLight,
    olive: SCENE_PALETTE.olive,
    oliveUi: SCENE_PALETTE.oliveUi,
    oliveLight: SCENE_PALETTE.oliveLight,
    olivePlan: SCENE_PALETTE.olivePlan,
    olivePlanDark: SCENE_PALETTE.olivePlanDark,
    terracotta: SCENE_PALETTE.terracotta,
    terracottaUi: SCENE_PALETTE.terracottaUi,
    terracottaHandle: SCENE_PALETTE.terracottaHandle,
    sand: SCENE_PALETTE.sand,
    metal: SCENE_PALETTE.metal,
    glass: SCENE_PALETTE.glass,
    fabric: SCENE_PALETTE.fabric,
    invalid: SCENE_PALETTE.invalid,
    invalidUi: SCENE_PALETTE.invalidUi,
    floorActive: SCENE_PALETTE.floorActive,
    floorInactive: SCENE_PALETTE.floorInactive,
    floorSideInactive: SCENE_PALETTE.floorSideInactive,
    wallInactive: SCENE_PALETTE.wallInactive,
    wallWoodActive: SCENE_PALETTE.wallWoodActive,
    wallWoodInactive: SCENE_PALETTE.wallWoodInactive,
    doorWood: SCENE_PALETTE.doorWood,
    outlineInactive: SCENE_PALETTE.outlineInactive,
    outline: SCENE_PALETTE.outline,
    detail: SCENE_PALETTE.detail,
    softCream: SCENE_PALETTE.softCream,
    bedInset: SCENE_PALETTE.bedInset,
    bedPillow: SCENE_PALETTE.bedPillow,
    handleDetail: SCENE_PALETTE.handleDetail,
    fog: SCENE_PALETTE.handleDetail,
    clearanceMargin: SCENE_PALETTE.clearanceMargin,
    wallPlan: SCENE_PALETTE.wallPlan,
    wallPlanEdge: SCENE_PALETTE.wallPlanEdge,
    dimensionLine: SCENE_PALETTE.dimensionLine,
    hatch: SCENE_PALETTE.hatch,
    gridMinor: SCENE_PALETTE.gridMinor,
    gridMajor: SCENE_PALETTE.gridMajor,
    lightWarm: SCENE_PALETTE.lightWarm,
    lightSky: SCENE_PALETTE.lightSky,
    lightGround: SCENE_PALETTE.lightGround,
  },
  plan: {
    wallThickness: 0.12,
    stroke: { hairline: 1, detail: 1.25, outline: 1.75, wall: 2.25 },
    dimension: { offset: 0.4, extension: 0.12, arrow: 0.11, gutter: 0.18 },
  },
  render: {
    shadowMapSize: 2048,
    maxDevicePixelRatio: 1.5,
    lineHitThreshold: 0.02,
  },
} as const

export const FURNITURE_SWATCHES = {
  olive: SCENE_PALETTE.oliveUi,
  leaf: SCENE_PALETTE.leaf,
  warmWood: SCENE_PALETTE.warmWood,
  darkWood: SCENE_PALETTE.darkWood,
  sand: SCENE_PALETTE.sand,
  cream: SCENE_PALETTE.cream50,
} as const
